retaxi/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from direcciones.views import ruta, lugares, detalle_lugar, getinfodire
from users.views import getPasajero, getConductor, asociarConductor
from conductores.views import ConductorDetail, ConductorList, MovilList, MovilDetail, actualizar_ubicacion, \
    ConductorViewSet, set_movil, remove_movil, conductor_msg_token, mapaMoviles
from mensajes.views import EnviarMensajeView
from pasajeros.views import PasajeroList, PasajeroDetail, pasajero_msg_token, pasajero_data_udt
from tarifas.views import TarifaDetail, TarifaList, prueba_calcular
from viajes.views import AceptarViajeView, PedirRemisView, ViajeListConductor, ViajeListPasajero, CancelarViajeView, iniciarViaje, finalizarViaje, \
    EnviarPosicion, puntuar_conductor, PedidosList, ViajeDetail, cambiarZona, cambiarEstado, PedidosFinalizados, cancelarPedido, editarPedido, editarZona, DetallePedido, asignarZona,cambiar_fechaAsignacion, quitarZona, pedidoChat, NuevoViajeList
from users.views import chat, ver_mensajes, enviarMensaje
from django.contrib.auth import views as auth_views
from django.conf import settings
from users.views import PasajeroLoginView, ConductorLoginView
from rviajes.views import RViajesList, RulesList
from zona.views import mapaZonas
from .views import mapa

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli urls
    #path('', include(router.urls)),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('auth/', include('rest_framework_social_oauth2.urls')),

    re_path('login/', auth_views.LoginView.as_view(), {'template_name': "login.html"},name='login'),
    re_path('logout/', auth_views.logout_then_login, name='logout'),

    re_path(r'^chat/$', view=chat, name='chat'),
    re_path(r'^mensajes/(?P<pk>[0-9]+)/', view=ver_mensajes, name='ver_mensajes'),

    re_path(r'^conductores/$', view=ConductorList.as_view()),
    re_path(r'^conductor/(?P<pk>\d+)/$',view=ConductorDetail.as_view()),
    re_path(r'^direcciones/ruta/([^/]+)/([^/]+)$', ruta),
    re_path(r'^direcciones/lugares/([^/]+)/([^/]+)$', lugares),    
    re_path(r'^direcciones/detalle_lugar/([^/]+)$', detalle_lugar),  
    re_path(r'^direcciones/getinfodire/([^/]+)$', getinfodire),   
    
    re_path(r'^get_pasajero/$', getPasajero),
    re_path(r'^get_conductor/$', getConductor),
    re_path(r'^asociar_conductor/$', asociarConductor),

    re_path(r'^login_pasajero/$', view=PasajeroLoginView.as_view(), name='pasajero_login'),
    re_path(r'^login_conductor/$', view=ConductorLoginView.as_view(), name='conductor_login'),

    re_path(r'^pasajeros/$', view=PasajeroList.as_view()),
    re_path(r'^pasajero/(?P<pk>\d+)/$', view=PasajeroDetail.as_view()),
    re_path(r'^moviles/$', view=MovilList.as_view()),
    re_path(r'^movil/(?P<pk>\d+)/$', view=MovilDetail.as_view()),
    re_path(r'^tarifas/$', view=TarifaList.as_view()),
    re_path(r'^tarifa/(?P<pk>\d+)/$', view=TarifaDetail.as_view()),
    re_path(r'^viajes_pasajero/$', ViajeListPasajero),
    re_path(r'^viajes_conductor/$', ViajeListConductor),
    re_path(r'^viaje/(?P<pk>\d+)/$', view=ViajeDetail.as_view()),
    re_path(r'^pedir_remis/$', view=PedirRemisView.as_view()),
    re_path(r'^aceptar_viaje/$', view=AceptarViajeView.as_view()),
    re_path(r'^cancelar_viaje/$', view=CancelarViajeView.as_view()),
    re_path(r'^envia_posicion/$', view=EnviarPosicion.as_view()),
    re_path(r'^enviar_msj/$', view=EnviarMensajeView.as_view()),
    re_path(r'^iniciar_viaje/$', iniciarViaje),
    re_path(r'^finalizar_viaje/$', finalizarViaje),
    re_path(r'^actualizar_ubicacion/$', actualizar_ubicacion),
    re_path(r'^calculartarifa/([^/]+)/([^/]+)$$', prueba_calcular),
    re_path(r'^puntuar_conductor/$', puntuar_conductor),
    re_path(r'^crear_movil/$', set_movil),
    re_path(r'^quitar_movil/$', remove_movil),
    re_path(r'^pasajero_msg_token/$', pasajero_msg_token),
    re_path(r'^pasajero_data_udt/$', pasajero_data_udt),
    re_path(r'^conductor_msg_token/$', conductor_msg_token),

    re_path(r'^pedidos/$', view=PedidosList, name='pedidos'),
    re_path(r'^finalizados/$', view=PedidosFinalizados.as_view(), name='finalizados'),
    re_path(r'^estado/', view=cambiarEstado, name='cambiar_estado'),
    re_path(r'^cancelar/', view=cancelarPedido, name='cancelar_pedido'),
    re_path(r'^asignarZona/', view=asignarZona, name='asignarZona'),
    re_path(r'^editarPedido/', view=editarPedido, name='editarPedido'),
    re_path(r'^editarZona/', view=editarZona, name='editarZona'),
    re_path(r'^cambiarZona/', view=cambiarZona, name='cambiarZona'),
    re_path(r'^quitarZona/', view=quitarZona, name='quitarZona'),
    re_path(r'^cambiar/', view=cambiar_fechaAsignacion, name='cambiar_fechaAsignacion'),
    re_path(r'^enviarMensaje/', view=enviarMensaje, name='enviarMensaje'),
    re_path(r'^pedidoChat/', view=pedidoChat, name='pedidoChat'),
    re_path(r'^detallePedido/(?P<pk>[0-9]+)/', view=DetallePedido.as_view(), name='detallePedido'),
    re_path(r'^mapaMoviles/', view=mapaMoviles, name='mapaMoviles'),

    re_path(r'^rreglas/', view=RulesList.as_view(), name='rreglas'),
    re_path(r'^rviajes/', view=RViajesList.as_view(), name='rviaje'),

    re_path(r'^nuevoViaje/$', view=NuevoViajeList, name='nuevoViaje'),
    re_path(r'^mapa/$', view=mapa, name='mapa'),

    re_path(r'^zonas/$', view=mapaZonas, name='zonas-list'),

]

viajes/models.py
from django.conf import settings
from django.contrib.gis.db import models
from django.utils import timezone
from conductores.models import Conductor
from pasajeros.models import Pasajero
from rviajes.models import RViaje
from zona.models import Zona
from django.dispatch import receiver
from django.db.models.signals import post_save
from datetime import datetime
from django.core import serializers


class Viaje(models.Model):
    STATUS = (
        ('P', 'Pendiente'),
        ('O', 'Completado'),
        ('E', 'En Curso'),
        ('B', 'Pasajero a Bordo'),
        ('F', 'Finalizado'),
        ('C', 'Cancelado')
    )
    TIPO = (
        ('M', 'Móvil'),
        ('T', 'Telefono'),
        ('W', 'WhatsApp'),
        ('D', 'Diferido'),
    )

    id = models.AutoField(primary_key=True)
    conductor = models.ForeignKey(
        Conductor, blank=True, null=True, on_delete=models.DO_NOTHING)
    pasajero = models.ForeignKey(
        Pasajero, blank=True, null=True, on_delete=models.DO_NOTHING)
    fecha_hora = models.DateTimeField(default=timezone.now,)
    origen = models.PointField(
        null=True, blank=True, default='POINT(0 0)', srid=4326)
    destino = models.PointField(
        null=True, blank=True, default='POINT(0 0)', srid=4326)
    fecha_hora_fin = models.DateTimeField(null=True)
    origen_descripcion = models.CharField(
        max_length=100, null=True, blank=True)
    destino_descripcion = models.CharField(
        max_length=100, null=True, blank=True)
    fecha_hora_inicio = models.DateTimeField(null=True)
    estado = models.CharField(
        max_length=1, choices=STATUS, default='P', null=True, blank=True)
    tipo = models.CharField(max_length=1, choices=TIPO,
                            default='M', null=True, blank=True)
    operador = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                 null=True, blank=True, related_name='viaje_operador')
    receptor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                 null=True, blank=True, editable=False, related_name='viaje_receptor')
    is_diferido = models.BooleanField(null=False, blank=False, default=False)
    comentario = models.CharField(max_length=60, null=True, blank=True)
    zona = models.ForeignKey(Zona, blank=True, null=True,
                             on_delete=models.DO_NOTHING)

    rviaje = models.ForeignKey(RViaje, on_delete=models.DO_NOTHING, null=True,
                               blank=True, editable=False, related_name='viaje_recurrente')

    class Meta:
        verbose_name = "viaje"
        verbose_name_plural = "viajes"

    def __str__(self):
        return super(Viaje, self).__str__()


class Calificacion(models.Model):
    conductor = models.ForeignKey(
        Conductor, blank=True, null=True, on_delete=models.DO_NOTHING)
    pasajero = models.ForeignKey(
        Pasajero, blank=True, null=True, on_delete=models.DO_NOTHING)
    viaje = models.ForeignKey(
        Viaje, blank=True, null=True, on_delete=models.DO_NOTHING)
    puntos_conductor = models.FloatField(blank=True, null=True, default=1)
    puntos_base = models.FloatField(blank=True, null=True, default=1)
    comentario = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        verbose_name = "Calificación"
        verbose_name_plural = "Calificaciones"

    def __str__(self):
        return super(Calificacion, self).__str__()


@receiver(post_save, sender=RViaje)
def crear_viajes(sender, instance, created, **kwargs):
    hora_ida = instance.start.time()
    fechas = list(instance.get_rrule_object())

    if created:
        v = []
        for f in fechas:
            v = Viaje.objects.create(conductor=instance.conductor,
                                     origen=instance.origen,
                                     destino=instance.destino,
                                     pasajero=instance.pasajero,
                                     origen_descripcion=instance.origen_descripcion,
                                     destino_descripcion=instance.destino_descripcion,
                                     fecha_hora=datetime.combine(f, hora_ida),
                                     fecha_hora_inicio=None,
                                     fecha_hora_fin=None,
                                     zona=instance.zona,
                                     tipo='D',
                                     operador=None,
                                     receptor=None,
                                     estado='P',
                                     is_diferido=True,
                                     rviaje=instance)

            # assuming obj is a model instance
            #serialized_obj = serializers.serialize('json', [ v, ])
            # print(serialized_obj)

        # Funca bien usar creted para crear y sino actualizar todos los viajes del mismo RViaje, q estan pendientes.
        # Por ahora trataría la creación no más
        # TRATAR LA VUELTAAAA !!!

templates/pedidos2.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="content-i">
  <div class="content-box row">

    <!--nav id="navigation">
      <div class="nav nav-tabs" id="nav-tab" role="tablist" style="margin-bottom: 10px;">
        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab"
          aria-controls="nav-home" aria-selected="true">Todos</a>
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab"
          aria-controls="nav-profile" aria-selected="false">En curso</a>
        <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab"
          aria-controls="nav-contact" aria-selected="false">Completados</a>
        <a class="nav-item nav-link" id="nav-abordo-tab" data-toggle="tab" href="#nav-abordo" role="tab"
          aria-controls="nav-abordo" aria-selected="false">A bordo</a>
      </div>
    </nav>

    <div class="tab-content" id="nav-tabContent">
      <div class="show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
    <div class="wrapper"-->
    <input id="baseUrl" type="hidden" value="{{ request.get_host }}" />
    <div class="col-sm-12 col-lg-8 col-xxl-8">
      <div class="wrapper">
        <div class="table-responsive">
          <table id="myTable" width="100%" class="tablas table table-striped table-lightfont">
            <thead>
              <tr>
                <th>
                  Pasajero
                </th>
                <th>
                  Origen
                </th>
                <th>
                  Destino
                </th>
                <th class="sorting_asc">
                  Hora
                </th>
                <th>
                  Zona
                </th>
                <th>
                  Movil
                </th>
                <th>
                  Estado
                </th>
                <th>
                  Accion
                </th>
              </tr>
            </thead>
            <tbody>
              {% for v in viajes %}
              <tr id="viaje{{v.id}}">
                <td>
                  {{v.comentario}}
                </td>
                <td>
                  <a href="{% url 'detallePedido' v.id %}" target="_blank">{{v.origen_descripcion}}</a>
                  <a href="#" data-target="#exampleModal1" data-toggle="modal"><i class="fa fa-info-circle"></i></a>
                </td>
                <td>
                  {{v.destino_descripcion}}
                </td>
                <td>
                  {{ v.fecha_hora|date:"j" }}-{{ v.fecha_hora|time:"H:i" }}
                </td>
                <td class="text-center" id="editarzona{{v.id}}">
                  {% if v.zona == None %}
                  Sin zona
                  {% else %}
                  {{v.zona.number}}
                  {% endif %}
                </td>
                <td class="text-center" id="conductor{{v.id}}" style="width: 100px;">
                  {% if v.estado == 'P' %}
                  <select class="form-control js-example-basic-single zona{{v.zona.pk}}" id="selectviaje{{v.id}}">

                    {% if v.zona == None %}
                    {% for y in conductores %}
                    <option value="{{y.dni}}">{{y.registro}}</option>
                    {% endfor %}
                    {% else %}

                    {% for c in  v.zona.obtenerConductores2 %}
                    <option value="{{c.dni}}" class="porzona{{c.dni}}">{{c.registro}}</option>
                    {% endfor %}

                    {% endif %}
                  </select>

                  {% else %}
                  {{v.conductor.registro}}
                  {% endif %}
                </td>
                <td class="text-center" id="estado{{v.id}}">
                  {% if v.estado == 'P' %}
                  <span class="badge badge-warning">{{v.get_estado_display}}</span></td>

                <td class="row-actions" id="accion{{v.id}}">
                  <a href="#" class="cambiarEstado" id="{{v.id}}"><i class="os-icon os-icon-arrow-down4"></i></a>
                  <a href="#" class="editarZona" id="{{v.id}}"><i class="os-icon os-icon-ui-49"></i></a>
                  <a href="#" class="cancelar" id="{{v.id}}"><i class="os-icon os-icon-cancel-circle"></i></a>
                </td>
                {% elif v.estado == 'E' %}
                <span class="badge badge-secondary">{{v.get_estado_display}}</span></td>
                <td class="row-actions" id="accion{{v.id}}">
                  <a href="#" class="cambiarEstado" id="{{v.id}}"><i class="os-icon os-icon-arrow-down4"></i></a>
                  <a href="#" class="editar" id="{{v.id}}"><i class="os-icon os-icon-ui-49"></i></a>
                  <a href="#" class="cancelar" id="{{v.id}}"><i class="os-icon os-icon-cancel-circle"></i></a>
                </td>
                {% elif v.estado == 'O' %}
                <span class="badge badge-secondary">{{v.get_estado_display}}</span></td>
                <td class="row-actions" id="accion{{v.id}}">
                  <a href="#" class="cambiarEstado" id="{{v.id}}"><i class="os-icon os-icon-arrow-down4"></i></a>
                  <a href="#" class="editar" id="{{v.id}}"><i class="os-icon os-icon-ui-49"></i></a>
                  <a href="#" class="cancelar" id="{{v.id}}"><i class="os-icon os-icon-cancel-circle"></i></a>
                </td>
                {% elif v.estado == 'B' %}
                <span class="badge badge-primary">{{v.get_estado_display}}</span></td>
                <td class="row-actions" id="accion{{v.id}}">
                  <a href="#" class="editar" id="{{v.id}}"><i class="os-icon os-icon-ui-49"></i></a>
                  <a href="#" class="cancelar" id="{{v.id}}"><i class="os-icon os-icon-cancel-circle"></i></a>
                </td>
                {% elif v.estado == 'C' %}
                <span class="badge badge-danger">{{v.get_estado_display}}</span></td>
                <td></td>
                {% endif %}



              </tr>
              <div aria-labelledby="exampleModalLabel" class="modal fade" id="exampleModal1" role="dialog" tabindex="-1"
                style="display: none;" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">{{v.comentario}} - {{v.origen_descripcion}}</h5>
                      <button aria-label="Close" class="close" data-dismiss="modal" type="button"><span
                          aria-hidden="true"> ×</span></button>
                    </div>
                    <div class="modal-body">
                      <p>{{v.comentario}}</p>
                    </div>
                    <div class="modal-footer"><button class="btn btn-secondary" data-dismiss="modal" type="button">
                        Cerrar</button></div>
                  </div>
                </div>
              </div>
              {%endfor%}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!--/div>
      </div>

      <!-- Viajes En curso 
      {% include 'pedidos_encurso_partial.html' %}
      <!-- Viajes Completados 
      {% include 'pedidos_completados_partial.html' %}
      <!-- Viajes a Bordo 
      {% include 'pedidos_abordo_partial.html' %}

    </div-->
    <!--Fin TAB Content-->

    <div class="col-sm-12 col-lg-4 col-xxl-4">
      <div class="wrapper2">
        <div class="content-panel compact color-scheme-dark" style="min-height: 100vh;">
          <div class="element-wrapper compact">
            <div class="element-actions actions-only">
              <a class="element-action element-action-fold" href="#"><i class="os-icon os-icon-minus-circle"></i></a>
            </div>
            <h6 class="element-header" style="margin-bottom: 0.5rem;">
              Asignar movil a zona
            </h6>
            <div class="element-box-tp">
              <div class="row">
                <div class="col-4">
                  <div class="form-group">
                    <label for=""> Zona</label>
                    <select class="form-control js-example-basic-single" id="select1" style="width: 100%;">
                      {% for z in zonas %}
                      <option value="{{z.pk}}" number="{{z.number}}">{{z.number}}-{{z.nombre}}
                      </option>
                      {% endfor %}
                    </select>
                  </div>
                </div>

                <div class="col-4">
                  <div class="form-group trobil">
                    <label for=""> Movil</label>
                    <select class="form-control js-example-basic-single" id="select2" style="width: 100%;">
                      {% for c in conductores %}
                      <option value="{{c.dni}}">{{c.registro}}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="col-4">
                  <div class="form-group">
                    <label for=""> </label>
                    <div class="chat-btn">
                      <a class="btn btn-primary asignarZona" href="#">Confirmar</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="element-wrapper compact">
            <div class="element-actions actions-only">
              <a class="element-action element-action-fold" href="#"><i class="os-icon os-icon-minus-circle"></i></a>
            </div>
            <h6 class="element-header" style="margin-bottom: 0.5rem;">
              Conductores por zona
            </h6>
            <div class="element-box-tp">
              <div class="row no-gutters">
                {% for z in zonas %}
                <div class="containerZonas col-sm text-center" id="lista{{z.id}}">
                  <div class="header no-drag">
                    <div class="name">{{z.number}}</div>
                    <strong id="count{{z.id}}" class="badge badge-danger">{{z.obtenerConductores2.count}}</strong>
                  </div>
                  <div class="itemes" id="itemes{{z.id}}">
                    {% for x in  z.obtenerConductores2 %}
                    {% if x.esAbonado == "true" %}
                    <div class="item" id="{{x.dni}}">
                      <div class="inactivo quitarZona" id="{{x.dni}}" style="cursor: pointer;">{{x.registro}}</div>
                    </div>
                    {% else %}
                    <div class="itemRojo" id="{{x.dni}}">
                      <div class="inactivo quitarZona" id="{{x.dni}}" style="cursor: pointer;">{{x.registro}}</div>
                    </div>
                    {% endif %}
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="snackbar"></div>


    </div>
    {% endblock content %}

    {% block extra_js%}
    <script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>
    <script src="{% static 'js/quick_access.js'%}"></script>
    <script src="{% static 'js/init_components.js'%}"></script>
    <script src="{% static 'js/dragdrop_movil_zona.js'%}"></script>
    <script src="{% static 'js/websockets_handle.js'%}"></script>

    <style>
      .mapclass {
        /* all maps */
        width: 500px;
        height: 200px;
      }
    </style>

    {% endblock extra_js%}

templates/pedidos_abordo_partial.html
<div class="tab-pane fade" id="nav-abordo" role="tabpanel" aria-labelledby="nav-abordo-tab">

    <div class="wrapper">
        <div class="col-sm-12 col-lg-12 col-xxl-12">
            <div class="table-responsive">
                <table id="myTable4" width="100%" class="tablas table table-striped table-lightfont">
                    <thead>
                        <tr>
                            <th>
                                Pasajero
                            </th>
                            <th>
                                Origen
                            </th>
                            <th>
                                Destino
                            </th>
                            <th class="sorting_asc">
                                Hora
                            </th>
                            <th>
                                Zona
                            </th>
                            <th>
                                Movil
                            </th>
                            <th>
                                Estado
                            </th>
                            <th>
                                Accion
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for b in abordo %}
                        <tr id="viaje{{b.id}}">
                            <td>
                                {{b.pasajero}}
                            </td>
                            <td>
                                <a href="{% url 'detallePedido' b.id %}" target="_blank">{{b.origen_descripcion}}</a>
                            </td>
                            <td>
                                {{b.destino_descripcion}}
                            </td>
                            <td>
                                {{ b.fecha_hora|time:"H:i" }}
                            </td>
                            <td class="text-center">
                                {% if b.zona == None %}Sin zona
                                {% else %}
                                {{b.zona}}
                                {% endif %}
                            </td>
                            <td class="text-center " id="conductor{{b.id}}" style="width: 100px;">
                                {% if b.estado == 'P' %}
                                <select class="form-control js-example-basic-single zona{{b.zona.pk}}"
                                    id="selectviaje{{b.id}}">

                                    {% if b.zona == None %}
                                    {% for y in conductores %}
                                    <option value="{{y.dni}}">{{y.registro}}</option>
                                    {% endfor %}
                                    {% else %}

                                    {% for c in  b.zona.obtenerConductores2 %}
                                    <option value="{{c.dni}}" class="porzona{{c.dni}}">{{c.registro}}</option>
                                    {% endfor %}

                                    {% endif %}
                                </select>

                                {% else %}
                                {{b.conductor.registro}}
                                {% endif %}
                            </td>
                            <td class="text-center" id="estado{{b.id}}">
                                {% if b.estado == 'B' %}
                                <span class="badge badge-primary">{{b.get_estado_display}}</span></td>
                            <td class="row-actions" id="accion{{b.id}}">
                                <a href="#" class="editar" id="{{b.id}}"><i class="os-icon os-icon-ui-49"></i></a>
                                <a href="#" class="cancelar" id="{{b.id}}"><i
                                        class="os-icon os-icon-cancel-circle"></i></a>
                            </td>
                            {% elif b.estado == 'C' %}
                            <span class="badge badge-danger">{{b.get_estado_display}}</span></td>
                            <td></td>
                            {% endif %}
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>

templates/pedidos_completados_partial.html
<div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">

    <div class="wrapper">
        <div class="col-sm-12 col-lg-12 col-xxl-12">
            <div class="table-responsive">
                <table id="myTable3" width="100%" class="tablas table table-striped table-lightfont">
                    <thead>
                        <tr>
                            <th>
                                Pasajero
                            </th>
                            <th>
                                Origen
                            </th>
                            <th>
                                Destino
                            </th>
                            <th class="sorting_asc">
                                Hora
                            </th>
                            <th>
                                Zona
                            </th>
                            <th>
                                Movil
                            </th>
                            <th>
                                Estado
                            </th>
                            <th>
                                Accion
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for o in completados %}
                        <tr id="viaje{{o.id}}">
                            <td>
                                {{o.pasajero}}
                            </td>
                            <td>
                                <a href="{% url 'detallePedido' o.id %}" target="_blank">{{o.origen_descripcion}}</a>
                            </td>
                            <td>
                                {{o.destino_descripcion}}
                            </td>
                            <td>
                                {{ o.fecha_hora|time:"H:i" }}
                            </td>
                            <td class="text-center" id="editarzona{{o.id}}">
                                {% if o.zona == None %}Sin zona
                                {% else %}
                                {{o.zona}}
                                {% endif %}
                            </td>
                            <td class="text-center " id="conductor{{o.id}}" style="width: 100px;">
                                {% if o.estado == 'P' %}
                                <select class="form-control js-example-basic-single zona{{o.zona.pk}}"
                                    id="selectviaje{{o.id}}">

                                    {% if o.zona == None %}
                                    {% for y in conductores %}
                                    <option value="{{y.dni}}">{{y.registro}}</option>
                                    {% endfor %}
                                    {% else %}

                                    {% for c in  o.zona.obtenerConductores2 %}
                                    <option value="{{c.dni}}" class="porzona{{c.dni}}">{{c.registro}}</option>
                                    {% endfor %}

                                    {% endif %}
                                </select>

                                {% else %}
                                {{o.conductor.registro}}
                                {% endif %}
                            </td>
                            <td class="text-center" id="completado{{o.id}}">
                                {% if o.estado == 'O' %}
                                <span class="badge badge-secondary">{{o.get_estado_display}}</span></td>
                            <td class="row-actions" id="acompletado{{o.id}}">
                                <a href="#" class="cambiarEstado" id="{{o.id}}"><i
                                        class="os-icon os-icon-arrow-down4"></i></a>
                                <a href="#" class="editar" id="{{o.id}}"><i class="os-icon os-icon-ui-49"></i></a>
                                <a href="#" class="cancelar" id="{{o.id}}"><i
                                        class="os-icon os-icon-cancel-circle"></i></a>
                            </td>
                            {% elif o.estado == 'B' %}
                            <span class="badge badge-primary">{{o.get_estado_display}}</span></td>
                            <td class="row-actions" id="acompletado{{o.id}}">
                                <a href="#" class="editar" id="{{o.id}}"><i class="os-icon os-icon-ui-49"></i></a>
                                <a href="#" class="cancelar" id="{{o.id}}"><i
                                        class="os-icon os-icon-cancel-circle"></i></a>
                            </td>
                            {% elif o.estado == 'C' %}
                            <span class="badge badge-danger">{{o.get_estado_display}}</span></td>
                            <td></td>
                            {% endif %}
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>